### ISSUE TITLE
Update Gradle version 

### ISSUE THREAD

**Issue by saurabh-mhaisekar** [hui-z/audio_player#5]
The plugin crahses with error

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_audio_player' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0
```

**Comment by arisros** [comment]
Do you installed google plugin? they said google update to androidx

I think we can try to use this way?

`
android.useAndroidX=true
android.enableJetifier=true
`

[https://stackoverflow.com/questions/59496368/execution-failed-for-task-flutter-twitterverifyreleaseresources](url)

[https://github.com/flutter/flutter/issues/46881](url)

I make PR for this [https://github.com/hui-z/audio_player/pull/6](url)

**Comment by saurabh-mhaisekar** [comment]
I am already using Android x.

**Comment by arisros** [comment]
the problem is not about your flutter app, its about `audio_player` not upgrade to androidx yet.

**Comment by 00Zion00** [comment]
If you have migrate to androidx, switch to master-androidx branch.
